### ISSUE TITLE
Allow passthrough of `exposeHeadRoute` route param

### ISSUE THREAD

**Issue by luke88jones** [fastify/under-pressure#148]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Expand the plugin's configuration options to allow the Fastify route option for `exposeHeadRoute` to be set.

Happy to do the work for this if you think it's a good idea.

### Motivation

Kubernetes needs an endpoint that responds with a 2XX or 3XX HTTP status code to check the health of the deployed service ([ref](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request)). I think it would be great to be able to re-use the under pressure endpoint for this functionality but currently this isn't possible as the Kubernetes check is a HEAD request. 

### Example

```JS
fastify.register(require('under-pressure'), {
  maxEventLoopDelay: 1000,
  exposeStatusRoute: {
    routeOpts: {
      exposeHeadRoute: true,
      logLevel: 'debug',
      config: {
        someAttr: 'value'
      }
    },
    routeSchemaOpts: { // If you also want to set a custom route schema
      hide: true
    },
    url: '/alive' // If you also want to set a custom route path and pass options
  }
})
```

**Comment by mcollina** [comment]
I think this is already supported, see https://github.com/fastify/under-pressure/blob/master/index.js#L98

**Comment by luke88jones** [comment]
Oh brilliant! I might raised a PR just to call that out a little clearer in the docs
