### ISSUE TITLE
How to find out in a custom healthCheck whether the service is under pressure?

### ISSUE THREAD

**Issue by budarin** [fastify/under-pressure#159]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Is custom healthCheck called after checking under pressure?
If no - we need In addition to the Db and Redis state, to know if the service is under pressure in order to form the correct answer.

**Comment by mcollina** [comment]
That's currently not exposed, but it can be added if you'd like to send a PR.

**Comment by budarin** [comment]
Unfortunately, I didn't understand your code very well, so I will have difficulties creating a PR.

In the code, you need to make a call to a custom healthCheck only if the service is not under pressure to make additional checks

**Comment by Eomm** [comment]
I think it is doable by a semaphore between these two options:

- https://github.com/fastify/under-pressure#pressure-handler
- https://github.com/fastify/under-pressure#custom-health-checks

the underPressure check and the healthCheck are concurrent and independent of each other
