### ISSUE TITLE
Use low-overhead native solution for event loop monitoring

### ISSUE THREAD

**Issue by mcollina** [fastify/under-pressure#18]
See https://github.com/mafintosh/event-loop-delay.

**Comment by mcollina** [comment]
It already implements that logic internally.

**Comment by delvedor** [comment]
Cool!

**Comment by cemremengu** [comment]
Does it run properly on windows though? 😄

**Comment by dnlup** [comment]
What about using https://nodejs.org/docs/latest-v12.x/api/perf_hooks.html#perf_hooks_perf_hooks_monitoreventloopdelay_options where available? is it something that could be considered?

**Comment by mcollina** [comment]
Definitely! Would you like to send a PR?

**Comment by dnlup** [comment]
Happy to!

**Comment by dnlup** [comment]
I have tried to address this in #46 . While working on it I realized I had already done something similar for metrics collection so I decided to publish it: https://github.com/dnlup/doc . I am just sharing in case you might find it useful.

I also have a question but maybe it does not belong to this discussion: do you think there could be a way this plugin could allow the user to set a custom way to provide for the metrics values (e.g. like a function or a custom decorator)?
