### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by SimenB** [fastify/under-pressure#184]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Would be nice to release 4023ba6eee48329547284c93fcf6859ec8720446 and 13e9781e55c312713980f90cd1ccb5ba97c51e07. Installing latest pulled in `@fastify/error@2` into the lockfile - all other `@fastify/*` deps in our project is using v3 😀

**Comment by Eomm** [comment]
Released v8 to work with fastify v4 👍🏽

**Comment by SimenB** [comment]
Thanks! I think it could have been a patch or minor (v6 already supported fastify v4), but it's just a number 😀

**Comment by SimenB** [comment]
Just need to update https://github.com/fastify/fastify-nextjs/blob/b17d8423d87e7a4247e13f17621aa5486f026da9/package.json#L46 then, and we should be good to go 👍

**Comment by Eomm** [comment]
> Thanks! I think it could have been a patch or minor (v6 already supported fastify v4), but it's just a number 😀

I saw there were some dropped nodejs versions on the CI files, so I went for safe

**Comment by SimenB** [comment]
Ah, good catch!
