### ISSUE TITLE
Ambiguous supported versions documentation

### ISSUE THREAD

**Issue by kibertoad** [fastify/under-pressure#191]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

x.xx

### Plugin version

x.xx

### Node.js version

x.xx

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

xxx

### Description

Currently documentation states this:
///
Since [eventLoopUtilization](https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_eventlooputilization_utilization1_utilization2) is only available in Node version 14.0.0 and 12.19.0 the check will be disabled in other versions.
///
I assume it actually works in 14.0.0+, not just that specific version, but documentation claims otherwise. It would be helpful to improve wording to make the intent clearer.

### Steps to Reproduce

Documentation issue

### Expected Behavior

///
Since [eventLoopUtilization](https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_eventlooputilization_utilization1_utilization2) is only available in Node versions 12.19.0, 14.0.0, and newer, the check will be disabled in other versions.
///

**Comment by mcollina** [comment]
Would you send a PR?

**Comment by kibertoad** [comment]
sure!
