### ISSUE TITLE
support for fastify 2? 

### ISSUE THREAD

**Issue by bkw** [fastify/under-pressure#21]
I see you've already added under-pressure to [the todo list for 2.0](https://github.com/orgs/fastify/projects/1), but still: Do you expect anthing to break by just bumping the version requirement? https://github.com/fastify/under-pressure/blob/1d8676c12bbf2ba9b00c6d241c331c19a0c6bc81/index.js#L113

**Comment by cemremengu** [comment]
Yes, it will break unfortunately. Expect a `next` release soon for Fastify 2

**Comment by bkw** [comment]
Alright, thanks for the notice and keep up the great work!

**Comment by cemremengu** [comment]
@bkw published to npm as `next`
