### ISSUE TITLE
Achieve 100% test coverage

### ISSUE THREAD

**Issue by gurgunday** [fastify/under-pressure#216]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

**Comment by jean-michelet** [comment]
Looking into it

**Comment by jean-michelet** [comment]
Wooo, I just noticed, did you realize that it will not launch the tests for `test/test.js`?
https://github.com/fastify/under-pressure/blob/4d311d6334edd0bd3aa95f5deba7f699f712963a/.taprc#L4

**Comment by jean-michelet** [comment]
I cover use cases that already exist in these files for 3 hours :smiling_face_with_tear:  
Plus, there are tests that fail to fix...

**Comment by jean-michelet** [comment]
@Uzlopak 

Can you confirm it was unintentional
https://github.com/fastify/under-pressure/commit/1cd9421e2e49c5a53de884bfe90fbf0b8047fa81
