### ISSUE TITLE
DeprecationWarning: request.context property access is deprecated.

### ISSUE THREAD

**Issue by ildella** [fastify/under-pressure#220]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28

### Plugin version

8.5.0

### Node.js version

22.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

23.10

### Description

This is the error stack:

```shell
(node:1086041) [FSTDEP012] DeprecationWarning: request.context property access is deprecated. Please use "request.routeOptions.config" or "request.routeOptions.schema" instead for accessing Route settings. The "request.context" will be removed in `fastify@5`.
    at DeprecationWarning (/project/node_modules/process-warning/index.js:71:15)
    at _Request.get (/project/node_modules/fastify/lib/request.js:176:7)
    at Object.onRequest (/project/node_modules/@fastify/under-pressure/index.js:224:34)

```

### Expected Behavior

Just update the code as suggested by Fastify deprecation warning.

**Comment by gurgunday** [comment]
A PR would be appreciated ;)

**Comment by ildella** [comment]
It has already been done here: https://github.com/ildella/under-pressure/commit/a650100e38ab1e4f8f9bcd305b50ef4a087fa7bf
