### ISSUE TITLE
Wrong typescript typing for customError

### ISSUE THREAD

**Issue by pasha-vuiko** [fastify/under-pressure#223]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.0

### Plugin version

8.5.0

### Node.js version

20.15.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.5

### Description

Wrong typescript typing for customError in plugin options, expected Error constructor, but in types we have Error instance

### Expected Behavior

Typing should be right, Error constructor instead of Error instance

**Comment by jean-michelet** [comment]
> Typing should be right, Error constructor instead of Error instance

It would cause a breaking change, we can perform an union: `customError?: Error | ErrorConstructor`.
