### ISSUE TITLE
Annoying deprecation warning in the npm version 

### ISSUE THREAD

**Issue by pasha-vuiko** [fastify/under-pressure#227]
Hello!

I'm using the last currently published version (8.5.0) of the package to NPM and I receive the annoying warning on the first request to the app:

``` 
(node:82372) [FSTDEP012] DeprecationWarning: request.context property access is deprecated. Please use "request.routeOptions.config" or "request.routeOptions.schema" instead for accessing Route settings. The "request.context" will be removed in `fastify@5`.
 (Use `node --trace-deprecation ...` to show where the warning was created)
```

That's because the `onRequest()` function in `index.js` uses `req.context.config`

```javascript
 function onRequest (req, reply, next) {
     const _pressureHandler = req.context.config.pressureHandler || pressureHandler
     ...
 }
```

But what I see in the master branch of the repository is that the issue is already fixed:

```javascript
 function onRequest (req, reply, next) {
     const _pressureHandler = req.routeOptions.config.pressureHandler || pressureHandler
     ...
 }
```

Could you please tell me when the next release to NPM is planned?

**Comment by Uzlopak** [comment]
We are currently preparing for fastify 5. So probably we wont release a patched version on npm?!

@fastify/leads

**Comment by jsumners** [comment]
Anyone is welcome to submit a PR against the current version's branch and issue a release.

**Comment by pasha-vuiko** [comment]
So could you please tell me how I can do it? Or by 'anyone' you mean 'anyone from maintainers team'?

**Comment by jean-michelet** [comment]
I think you should take a look at the branch v8.x: https://github.com/fastify/under-pressure/tree/v8.x

**Comment by jsumners** [comment]
> I think you should take a look at the branch v8.x: [`v8.x`](https://github.com/fastify/under-pressure/tree/v8.x?rgh-link-date=2024-07-04T06%3A04%3A30Z)

Correct.

> @jsumners could you please tell me how I can do it? Or by 'anyone' you mean 'anyone from maintainers team'?

I mean any interested party can contribute the fix.

**Comment by ildella** [comment]
It should be enouch to issue a PR against 8.x branch with this fix already in master
https://github.com/fastify/under-pressure/commit/a650100e38ab1e4f8f9bcd305b50ef4a087fa7bf#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L224-R224 @pasha-vuiko 

And then what, if CI is green how can we get a release? @jsumners

**Comment by climba03003** [comment]
> And then what, if CI is green how can we get a release?

I don't see anyone send PR to `8.x`. When PR merge, we will then release.

**Comment by ildella** [comment]
> > And then what, if CI is green how can we get a release?
> 
> I don't see anyone send PR to `8.x`. When PR merge, we will then release.

I am afraid that's not clear to me. 
There are no PR for 8.x now, for sure. 
But I can make one. If so, and provided CI is green, we can then have a release?
