### ISSUE TITLE
Additional route options are not passed when exposing status route

### ISSUE THREAD

**Issue by barrydobson** [fastify/under-pressure#42]
## 🐛 Bug Report

When attempting to change the log level of the status route, the option is not passed along when under-pressure builds the route.

## To Reproduce

```js
fastify.register(require('under-pressure'), {
      maxEventLoopDelay: 1000,
      maxHeapUsedBytes: 100000000,
      maxRssBytes: 100000000,
      exposeStatusRoute: true,
      logLevel: 'silent'
    });
```
 When hitting the `./status` route I can still see the request and response logs, which will clutter up the log files.

## Expected behavior

when setting options for the plugin, they should be forwarded to the route registration in under-pressure.

## Your Environment

- *node version*: 8
- *fastify version*: ^2.10.0
- *under-pressure version*: ^3.1.0 

I'm happy to submit a PR to resolve the issue if required.

**Comment by mcollina** [comment]
Good catch! Would you mind to send a PR?
Il 27 nov 2019, 09:46 +0000, Barry Dobson <notifications@github.com>, ha scritto:
