### ISSUE TITLE
Use custom Error instance

### ISSUE THREAD

**Issue by mslabik** [fastify/under-pressure#54]
## 🚀 Feature Proposal

Custom error thrown & exported from lib. Allow to override Error instance.

## Motivation

It's hard to distinguish if error comes from plugin, the only way is to check string message.

## Example
In fastify error handler
```js
const { UnderPressureError }  = require('under-pressure'); 

const errorHandler = async (err, req, reply) => {
    if (err instanceof UnderPressureError) {
        return sendCustomError(reply, 'Service is under pressure.', E_10000_GENERIC, SERVICE_UNAVAILABLE);
    }
}
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by delvedor** [comment]
@mcollina it would be nice to expose a simple API to plugins the internal Fastify function that we are using for creating errors. What do you think?

**Comment by mcollina** [comment]
That would be handy, yes.

**Comment by delvedor** [comment]
If someone would like to take a stab with this, you can now use [fastify-error](https://github.com/fastify/fastify-error) for generating custom errors :)
