### ISSUE TITLE
How to hide it's default route created by exposeStatusRoute:'/live' in swagger ui.

### ISSUE THREAD

**Issue by Harshitparsai** [fastify/under-pressure#60]
![Screenshot from 2020-08-17 15-04-34](https://user-images.githubusercontent.com/37847566/90382556-88088080-e09c-11ea-95ff-e2bdf23b0f03.png)

## Example

  fastify.register(async function (fastify) {
    fastify.register(underPressure, {

      maxEventLoopDelay: fastify.config.MAX_EVENT_LOOP_DELAY,
      maxHeapUsedBytes: fastify.config.MAX_HEAP_USED_BYTES,
      maxRssBytes: fastify.config.MAX_RSS_BYTES,

      exposeStatusRoute: "/live",
    });

**Comment by Eomm** [comment]
You can't archive it right now :(

To archive it, we should be able to decorate the `schema` option here:

https://github.com/fastify/under-pressure/blob/213f8999a620f572531165cdec0b57255d879784/index.js#L84

adding the `hide: true` parameter

```
fastify.register(underPressure, {
  exposeStatusRoute: {
    routeOpts: {
      logLevel: 'debug',
      config: {
        someAttr: 'value'
      }
    },
   routeSchemaOpts: { hide: true}, // this add to the default schema object new customization
    url: '/live' 
  }
})
```


Would you like to send a PR?
