### ISSUE TITLE
use eventLoopUtilization if it is available

### ISSUE THREAD

**Issue by mcollina** [fastify/under-pressure#65]
## 🚀 Feature Proposal

Node v14.10.0 shipped a more precise way to check on the event loop utilization:
https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_eventlooputilization_utilization1_utilization2

This module should use that if it is available.

**Comment by sujeshthekkepatt** [comment]
Can I work on this @mcollina ? Could you give more insights?

**Comment by mcollina** [comment]
go for it!

**Comment by sujeshthekkepatt** [comment]
Could you give me a little more information on this @mcollina ?

**Comment by mcollina** [comment]
Currently this is using the event loop delay as a proxy for the event loop utilization. If the event loop utilization is close to 1 (or 1) in an interval, it is better to start kicking off the protection.
Rather than replacing the delay as the title, add this new metric.

**Comment by sujeshthekkepatt** [comment]
Thanks for the reply @mcollina . This is my first encounter with `fastify`  ecosystem :). Based on the feedback, I think the following need to take place,

- Make a new option for setting a maximum threshold value for eg:`maxEventLoopUtlization` 

-  Set a variable for measuring event loop utilization for `elu=eventLoopUtilization()`

-  Add a function for checking eventloop utilization in `updateMemoryUsage` with the following signature,

``` 
function updateEventLoopUtilization () {
    if (elu) {
      eventLoopUtilizationVal = Math.max(0, eventLoopUtilization(elu).utilization)
    } else {
      eventLoopUtilizationVal = 0;
    }
  }
//`eventLoopUtilizationVal` is a global variable used to measure the utilization value.
```

- Compare the user threshold with `eventLoopUtilizationVal` and based on that send a 503 response.

Thoughts @mcollina

**Comment by mcollina** [comment]
I would not use the max.

Overall, +1!

**Comment by sujeshthekkepatt** [comment]
The one thing I have doubts about is tests. Since `eventLoopUtilization` available only in `v12.19.0`  and `v14.0.0` the tests will fail in versions other than that. So I have some doubts there. Any thoughts @mcollina . Sorry for the continues mentioning :)

**Comment by kibertoad** [comment]
@sujeshthekkepatt Couldn't you make test conditional and do not execute it on versions below? (probably `semver` library would be helpful here)

**Comment by sujeshthekkepatt** [comment]
> @sujeshthekkepatt Couldn't you make test conditional and do not execute it on versions below? (probably `semver` library would be helpful here)
Yeah, I could do that. I can add `semver` as a dev dependency and can skip the test on unsupported versions. So skipping the test won't be a problem, right @kibertoad ?

**Comment by sujeshthekkepatt** [comment]
> @sujeshthekkepatt Couldn't you make test conditional and do not execute it on versions below? (probably `semver` library would be helpful here)

I can skip the test conditional on unsupported versions. So skipping the test won't be a problem in this scenario, right @kibertoad
